### ISSUE TITLE
VIEW IT LIVE Button always disabled

### ISSUE THREAD

**Issue by fernandospr** [Augment/Samples#1]
I've edited the com/augment/acmeshop/ACMEShop.java file with the corresponding credentials. 
Launched the app.
All the products have the VIEW IT LIVE button disabled.

I've debugged and saw that when you call `checkIfModelDoesExistForUserProductQuery` it will call `onResponse` with a null augmentProduct.

**Comment by mmorisset** [comment]
Hi thanks for your feedback,

When you are integrating our Mobile SDK, you only have access to your catalog of products, the products defined in this sample doesn't belong to your catalog this is why it returns null.

This sample is provided as documentation on how to use our SDK it was not meant to be compiled into a working app but as we have a lot of people asking for a live demo we will push it to stores and provide a link in the documentation.

Don't hesitate if you need more assistance

**Comment by mmorisset** [comment]
We will comment and close this issue when the sample is released

**Comment by jrmgx** [comment]
We now provide demo API keys in our samples,
thank you again for your feedback.
